// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// approx_complete_data_loglik_rcpp
NumericMatrix approx_complete_data_loglik_rcpp(const NumericMatrix& Y, const NumericVector& M, const NumericVector& W, const NumericVector& sigma2);
RcppExport SEXP _scDEcrypter_approx_complete_data_loglik_rcpp(SEXP YSEXP, SEXP MSEXP, SEXP WSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(approx_complete_data_loglik_rcpp(Y, M, W, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// de_mu_rcpp
NumericVector de_mu_rcpp(const NumericMatrix& Y, const NumericVector& W, const IntegerVector& comp_idx);
RcppExport SEXP _scDEcrypter_de_mu_rcpp(SEXP YSEXP, SEXP WSEXP, SEXP comp_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type comp_idx(comp_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(de_mu_rcpp(Y, W, comp_idx));
    return rcpp_result_gen;
END_RCPP
}
// de_mu_null_rcpp
NumericVector de_mu_null_rcpp(const NumericMatrix& Y, const NumericVector& W, const IntegerVector& comp_idx);
RcppExport SEXP _scDEcrypter_de_mu_null_rcpp(SEXP YSEXP, SEXP WSEXP, SEXP comp_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type comp_idx(comp_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(de_mu_null_rcpp(Y, W, comp_idx));
    return rcpp_result_gen;
END_RCPP
}
// de_sigma2_rcpp
NumericVector de_sigma2_rcpp(const NumericMatrix& Y, const NumericVector& W, const NumericVector& M);
RcppExport SEXP _scDEcrypter_de_sigma2_rcpp(SEXP YSEXP, SEXP WSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(de_sigma2_rcpp(Y, W, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scDEcrypter_approx_complete_data_loglik_rcpp", (DL_FUNC) &_scDEcrypter_approx_complete_data_loglik_rcpp, 4},
    {"_scDEcrypter_de_mu_rcpp", (DL_FUNC) &_scDEcrypter_de_mu_rcpp, 3},
    {"_scDEcrypter_de_mu_null_rcpp", (DL_FUNC) &_scDEcrypter_de_mu_null_rcpp, 3},
    {"_scDEcrypter_de_sigma2_rcpp", (DL_FUNC) &_scDEcrypter_de_sigma2_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_scDEcrypter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
